version: '3.1'
services:
  gdb:
    build: .
    container_name: neo4j    
    privileged: true
    hostname: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms.memory.heap.initial_size=1G
      - NEO4J_dbms_memory_heap_max__size=1G        
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_AUTH=neo4j/test      
      # - NEO4J_dbms_shell_enabled=true
      # - NEO4J_apoc_export_file_enabled=true
      # - NEO4J_apoc_import_file_enabled=true      
      # - NEO4J_apoc_import_file_use__neo4j__config=true
      # - NEO4JLABS_PLUGINS=\[\"apoc\"\]
      # - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      # - NEO4J_dbms_connector_https_advertised__address=localhost:7473
      # - NEO4J_dbms_connector_http_advertised__address=localhost:7474
      # - NEO4J_dbms_connector_bolt_advertised__address=localhost:7687
      # - dbms.connectors.default_listen_address=200.150.11.15
    volumes:
      - ./db_extend/plugins:/var/lib/neo4j/plugins
      - ./db_extend/data:/var/lib/neo4j/data
      - ./db_extend/import:/var/lib/neo4j/import
      - ./home:/home/neo4j
      - ./db_extend/conf:/var/lib/neo4j/conf
      - ./db_extend/logs:/var/lib/neo4j/logs